#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#   (1) You need a POSIX-compliant shell to run this script.
#   (2) You need a JDK 17+ to run this script.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
        /*)   app_path=$link ;;
        *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available heap, but at least 64 MB
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Add default JVM options here
exec_dir=""
for opt in $DEFAULT_JVM_OPTS; do
    exec_dir="$exec_dir $opt"
done

exec "$APP_HOME/gradlew" "$@"